name: My  github enviornmental variable workflow
on:
  push:
    branches:
      - "main"
jobs:
  run-shell-command: 
    runs-on: ubuntu-latest  
    steps:
      - name: Printing Global variable  
        run: |
          echo "${{ secrets.NODE_ENV }}"
          NODE_ENV=$(echo "${{ secrets.NODE_ENV }}" | sed 's/./& /g')
          echo "NODE_ENV: $NODE_ENV"