name: My  github enviornmental variable workflow
on:
  push:
    branches:
      - "main"
jobs:
  run-shell-command: 
    runs-on: ubuntu-latest  
    steps:
      - name: Printing Global variable  
        run: |
          echo "${{ secrets.NODE_ENV }}"
          NODE_ENV=$(echo "${{ secrets.NODE_ENV }}" | sed 's/./& /g')
          echo "NODE_ENV: $NODE_ENV"
      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Store secret in Azure Key Vault
        env:
          AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
          AZURE_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
          AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
          KEY_VAULT_NAME: "opstree-poc-vault"
          SECRET_NAME: "NODE_ENV"
          SECRET_VALUE: "${{ secrets.NODE_ENV }}"
        run: |
          az login --service-principal -u $AZURE_CLIENT_ID -p $AZURE_CLIENT_SECRET -t $AZURE_TENANT_ID
          az keyvault secret set --vault-name $KEY_VAULT_NAME --name $SECRET_NAME --value $SECRET_VALUE          