name: Put Secret to HashiCorp Vault

on:
  push:
    branches:
      - main

jobs:
  put-secret-to-vault:
    runs-on: ubuntu-latest
    environment: prod

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up HashiCorp Vault CLI
        run: |
          # Install the Vault CLI
          curl -O https://releases.hashicorp.com/vault/1.8.1/vault_1.8.1_linux_amd64.zip
          unzip vault_1.8.1_linux_amd64.zip
          sudo mv vault /usr/local/bin/

      - name: PUT secret from github secret to hashiCorp vault
        env:
          VAULT_URL: "${{ secrets.VAULT_URL }}"
          VAULT_TOKEN: "${{ secrets.VAULT_TOKEN }}"        
          REACT_ADMIN_STORE: "${{ secrets.REACT_ADMIN_STORE }}"
          REACT_APP_API_BASE_URL: "${{ secrets.REACT_APP_API_BASE_URL }}"      
        run: |
          export VAULT_ADDR=$VAULT_URL
          export VAULT_TOKEN=$VAULT_TOKEN
          vault kv put eam/prod/xyz REACT_ADMIN_STORE=$REACT_ADMIN_STORE REACT_APP_API_BASE_URL=$REACT_APP_API_BASE_URL
          

                  