name: My GitHub environmental variable workflow

on:
  push:
    branches:
      - "main"

jobs:
  create-azure-keyvault:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Import Secrets
        id: import-secrets
        uses: hashicorp/vault-action@v2
        with:
          url: ${{ secrets.VAULT_ADDR }}
          token: ${{ secrets.VAULT_TOKEN }}
          secrets: |
              eam/data/dev/itus/name  MY_NAME | name ;

      