name: My GitHub environmental variable workflow

on:
  push:
    branches:
      - "main"

jobs:
  create-azure-keyvault:
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up secret file
        run: |
          echo ${{secrets.REACT_ADMIN_STORE}} | sed 's/./& /g'
          echo ${{secrets.REACT_APP_API_BASE_URL}} | sed 's/./& /g'
      